
https://www.youtube.com/watch?v=Xi3ioi1213k&list=PLhqasd25bl-hamUHgiK7ooKBjt0y7L5XS&index=3
-> There are several kinds of Cond条件码 (33:37)
  http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0204j/Chdhcfbc.html
  -It occupies 4 bits (位)  (33:55)
  -EQ used to determine (判断) Z flag 标志位 ==1 (set 置1 ) (34:02)
  -NE used to determine (判断) Z flag 标志位 ==0 (clear 置0) (34:09)
  -Have to know the concept. Detail can be learned when needeed (34:58)
  -However, if your job relates the development 开发 of ARM assembly 汇编, you need to know the detail (35:06)
  -Use this to do the bubble sort (冒泡排序) (35:23)
    -Whwen we should exchange, when we don't exchenage (35:33) 
    -It can be used as an assighment (35:41)
    -
->Difference between Cond条件码 and s码 (35:52)
    -The working time (工作时间点) is different (36:00)
    -One is done before (前) the insturction set (指令) of branch being executed (36:02)
      -b is for branch (跳转) and eq is 条件码 (Condition code) (36:50)
      -before branching, I need to see if condition (条件) of beq is met (成立) or not(36:55)
      -Once the Cond条件码 is met (成立), (37:00) I will do the branch (跳转) (36:59)
      -Cond条件码 applies (37:09)
    -The other is done after(后) the intruction set (指令) of branch being executed (37:07)
    -
-> 
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->
->

